# Generated by Django 4.2.10 on 2024-03-09 05:02

import catalog.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
                (
                    "name",
                    models.TextField(
                        blank=True,
                        validators=[django.core.validators.MaxLengthValidator(150)],
                        verbose_name="Название",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        validators=[django.core.validators.MaxLengthValidator(200)],
                        verbose_name="Слаг",
                    ),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                1, message="Значение должно быть больше 0"
                            ),
                            django.core.validators.MaxLengthValidator(
                                32767, message="Значение должно быть меньше 32678"
                            ),
                        ],
                        verbose_name="Вес",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ("weight", "id"),
            },
        ),
        migrations.CreateModel(
            name="ImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="catalog/",
                        verbose_name="Будет приведено к ширине 1280px",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото",
                "verbose_name_plural": "Фото",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
                (
                    "name",
                    models.TextField(
                        blank=True,
                        validators=[django.core.validators.MaxLengthValidator(150)],
                        verbose_name="Название",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        unique=True,
                        validators=[django.core.validators.MaxLengthValidator(200)],
                        verbose_name="Слаг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
                (
                    "name",
                    models.TextField(
                        blank=True,
                        validators=[django.core.validators.MaxLengthValidator(150)],
                        verbose_name="Название",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        help_text="Опишите объект",
                        validators=[catalog.validators.custom_text_validator],
                        verbose_name="Текст",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Выберите категорию",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.category",
                        verbose_name="категория",
                    ),
                ),
                (
                    "main_image",
                    models.ForeignKey(
                        help_text="Загрузите фото товара",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.imagemodel",
                        verbose_name="главная фотография",
                    ),
                ),
                ("tags", models.ManyToManyField(to="catalog.tag")),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
