# Generated by Django 4.2.10 on 2024-02-27 07:14

import catalog.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
                (
                    "name",
                    models.TextField(
                        blank=True,
                        validators=[django.core.validators.MaxLengthValidator(150)],
                        verbose_name="Название",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        unique=True,
                        validators=[django.core.validators.MaxLengthValidator(200)],
                        verbose_name="Слаг",
                    ),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(default=100, verbose_name="Вес"),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
                (
                    "name",
                    models.TextField(
                        blank=True,
                        validators=[django.core.validators.MaxLengthValidator(150)],
                        verbose_name="Название",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        unique=True,
                        validators=[django.core.validators.MaxLengthValidator(200)],
                        verbose_name="Слаг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
                (
                    "name",
                    models.TextField(
                        blank=True,
                        validators=[django.core.validators.MaxLengthValidator(150)],
                        verbose_name="Название",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        help_text="Опишите объект",
                        validators=[catalog.models.custom_text_validator],
                        verbose_name="Текст",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.category",
                    ),
                ),
                ("tags", models.ManyToManyField(to="catalog.tag")),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
