# Generated by Django 4.2.10 on 2024-03-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_imagemodel_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagemodel",
            name="image",
            field=models.ImageField(
                default="media/catalog/suit_1.jpg",
                upload_to="catalog/",
                verbose_name="Будет приведено к ширине 1280px",
            ),
        ),
    ]
