# Generated by Django 4.2.10 on 2024-03-09 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_imagemodel_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="weight",
            field=models.PositiveSmallIntegerField(
                default=100,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Значение должно быть больше 0"
                    ),
                    django.core.validators.MaxValueValidator(
                        32767, message="Значение должно быть меньше 32678"
                    ),
                ],
                verbose_name="Вес",
            ),
        ),
        migrations.AlterField(
            model_name="imagemodel",
            name="image",
            field=models.ImageField(
                default="catalog/suit_1.jpg",
                upload_to="catalog/",
                verbose_name="Будет приведено к ширине 1280px",
            ),
        ),
    ]
