# Generated by Django 4.2.10 on 2024-03-16 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_image_mainimage_remove_item_main_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(150)],
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(150)],
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(150)],
                verbose_name="Название",
            ),
        ),
    ]
