# Generated by Django 4.2.10 on 2024-03-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_category_name_alter_item_name_alter_tag_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_on_main",
            field=models.BooleanField(default=True, verbose_name="на главной странице"),
        ),
    ]
